name = "Esoteria"
author = "CantWeAllDisagree"
version = "0.00.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "fb4ad587cd3db1354134424f382f0de1085c412fe322774dbd5ef4cdcfc03f5a"

[versions]
fabric = "0.14.25"
minecraft = "1.19.2"

[options]
acceptable-game-versions = ["1.19.1"]
datapack-folder = "config/paxi/datapacks"
