name = "Esoteria"
author = "CantWeAllDisagree"
version = "0.00.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8db5db82bc062fd68d6ca3638a08e953601381edf34813a83bc376ace0d23d5a"

[versions]
fabric = "0.14.25"
minecraft = "1.19.2"

[options]
acceptable-game-versions = ["1.19.1"]
datapack-folder = "config/paxi/datapacks"
