name = "Esoteria"
author = "CantWeAllDisagree"
version = "0.00.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "68ab44378b59df04fd08b24f84d1d61b401c909f3a84fd2a2bf49e194452e2ab"

[versions]
fabric = "0.14.25"
minecraft = "1.19.2"

[options]
acceptable-game-versions = ["1.19.1"]
datapack-folder = "config/paxi/datapacks"
