name = "Esoteria"
author = "CantWeAllDisagree"
version = "0.00.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c3c2e9500d8f38f6f8f1fdada5172ca9b26fc4a190cb4258a671d9c6a281e8e2"

[versions]
fabric = "0.14.25"
minecraft = "1.19.2"

[options]
acceptable-game-versions = ["1.19.1"]
datapack-folder = "config/paxi/datapacks"
